services:
  postgres:
    image: postgres:16
    container_name: pg_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${ACCOUNT_DB_NAME}
      POSTGRES_USER: ${ACCOUNT_DB_USERNAME}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ACCOUNT_DB_USERNAME} -d ${ACCOUNT_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Database config
      SPRING_DATASOURCE_URL: ${ACCOUNT_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${ACCOUNT_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ACCOUNT_DB_PASSWORD}

      # Redis config (bạn cần dùng trong Spring Boot)
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      # Các config khác
      APP_EMAIL: ${APP_EMAIL}
      APP_PASSWORD: ${APP_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      BASE_64: ${BASE_64}
    ports:
      - "8081:8081"

  pgbackups:
    image: prodrigestivill/postgres-backup-local:16
    container_name: pg_backups
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${ACCOUNT_DB_NAME}
      POSTGRES_USER: ${ACCOUNT_DB_USERNAME}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASSWORD}
      POSTGRES_EXTRA_OPTS: -Z9 --schema=public --blobs
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: "7"
      BACKUP_KEEP_WEEKS: "4"
      BACKUP_KEEP_MONTHS: "6"
      HEALTHCHECK_PORT: "8081"
    volumes:
      - ./backups:/backups

volumes:
  pgdata:
  redisdata:
